//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblActivos()
        {
            this.TblPrestamosResueltos = new HashSet<TblPrestamosResueltos>();
            this.TblTrasladoActivo = new HashSet<TblTrasladoActivo>();
        }
    
        public string patrimonio { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public string disponibilidad { get; set; }
    
        public virtual TblActivoSolicitado TblActivoSolicitado { get; set; }
        public virtual TblMovimientoActivo TblMovimientoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrestamosResueltos> TblPrestamosResueltos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTrasladoActivo> TblTrasladoActivo { get; set; }
    }
}
