//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmpleado()
        {
            this.TblMovimiento = new HashSet<TblMovimiento>();
        }
    
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string condicion { get; set; }
        public string estado { get; set; }
        public string codigoSede { get; set; }
        public string idDepartamento { get; set; }
    
        public virtual TblDepartamento TblDepartamento { get; set; }
        public virtual TblUnidadOrganizativa TblUnidadOrganizativa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimiento> TblMovimiento { get; set; }
        public virtual TblPlaza TblPlaza { get; set; }
        public virtual TblUbicacion TblUbicacion { get; set; }
    }
}
