//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMovimiento()
        {
            this.TblMovimientoActivo = new HashSet<TblMovimientoActivo>();
            this.TblMovimientoConsumibles = new HashSet<TblMovimientoConsumibles>();
            this.TblPrestamosResueltos = new HashSet<TblPrestamosResueltos>();
        }
    
        public int idMovimiento { get; set; }
        public string nombreUsuario { get; set; }
        public string cedEmpleado { get; set; }
        public string observacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
    
        public virtual TblEmpleado TblEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimientoActivo> TblMovimientoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimientoConsumibles> TblMovimientoConsumibles { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPrestamosResueltos> TblPrestamosResueltos { get; set; }
    }
}
