//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPrestamosResueltos
    {
        public int idMovimiento { get; set; }
        public string patrimonio { get; set; }
        public int resuelto { get; set; }
    
        public virtual TblActivos TblActivos { get; set; }
        public virtual TblMovimiento TblMovimiento { get; set; }
    }
}
