//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTraslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTraslado()
        {
            this.TblTrasladoActivo = new HashSet<TblTrasladoActivo>();
            this.TblTrasladoConsumibles = new HashSet<TblTrasladoConsumibles>();
        }
    
        public int idTraslado { get; set; }
        public string nombreUsuario { get; set; }
        public string unidadSalida { get; set; }
        public string unidadDestino { get; set; }
        public System.DateTime fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTrasladoActivo> TblTrasladoActivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTrasladoConsumibles> TblTrasladoConsumibles { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUnidadOrganizativa TblUnidadOrganizativa { get; set; }
        public virtual TblUnidadOrganizativa TblUnidadOrganizativa1 { get; set; }
    }
}
